##########################################
#         MinigameManager config         #
#              by DonkeyCore             #
##########################################

# Language to use for messages (must reload plugin to take effect)
language: en_US

# Everything to do with rotations and the rotation lobby
rotations:
  # The amount of rotations in total (requires reload)
  amount: 1
  # Minimum players required to join a game
  # NOTE - A minigame that requires more players
  # than the current amount will not start until
  # there is enough players to do so
  minimum-players: 5
  # Additional players cannot join this rotation when the maximum is reached
  maximum-players: 10
  # The time to count down each time a new minigame is ready to play
  countdown-seconds: 30
  # Whether people in different rotations can see each other in the lobby
  lobby-hide-players: true
  # When somebody joins the server, automatically assign them to a rotation and let them leave on quit
  entire-server: false

# Configuration for when players join the lobby
lobby:
  # Whether players can take damage in the lobby
  damage: false
  # Whether players can lose hunger in the lobby
  hunger: false
  # Whether to display the lobby scoreboard
  scoreboard: true

# Minigame-specific configuration
minigames:
  # Configure the default minigames
  default-minigames:
    # Should any default minigames be in the rotation? (requires reload)
    enabled: true
    # Configure each default minigame specifically
    defaults:
      Spleef:
        # Should this minigame be in the rotation? (takes effect after next minigame finishes or reload)
        enabled: true
        # Minimum players required to start, the more the merrier! (takes effect after next minigame finishes or reload)
        minimum-players: 5
      One_In_The_Quiver:
        enabled: true
        minimum-players: 5

# Configuration for currency awarded after games
currency:
  # Whether to use the prefix for currency, or the suffix
  use-prefix: true
  # Prefix for the currency. Example below is the dollar sign
  prefix: "$"
  # Suffix for the currency. Example below is " gems"
  suffix: " gems"
  # How the currency will be referred to in scoreboards and such
  name: "Money"

# Profiles for all players that play minigames
profiles:
  # Configuration for the ELO ranking system that places
  # players in rotations with players of similar experience
  # For more information, see https://en.wikipedia.org/wiki/Elo_rating_system
  elo:
    # Whether to enable ELO ranking
    enabled: true
    # The default ELO rating for new players
    default: 1000
  # Whether to enable Vault economy instead of the internal one
  # If true, Vault needs to be installed (duh!)
  vault: false

# Optional MySQL configuration
mysql:
  # Whether to use config files or a MySQL database
  enabled: false
  # IP of the database
  ip: "127.0.0.1"
  # Port of the database
  port: 3306
  # Database name
  database: "minigamemanager"
  # Username for the database
  username: "root"
  # Password for the database (leave blank if none, but that's not recommended)
  password: ""
  # Names of tables
  tables:
    # Name for the table that contains all the profiles of players
    profiles: "profiles"
