name: MinigameManager
version: 0.0.1
description: "Minigame API and rotation handler"
main: me.donkeycore.minigamemanager.core.MinigameManagerPlugin
author: DonkeyCore
softdepend: [Vault]
commands:
  join:
    description: "Join the minigame rotation"
    permission: minigamemanager.join
    usage: "§cUsage: /<command> [rotation]"
  leave:
    description: "Leave the minigame rotation"
    permission: minigamemanager.leave
    usage: "§cUsage: /<command>"
  minigamemanager:
    description: "Main plugin administration command"
    permission: minigamemanager.admin
    usage: "§cUsage: /<command> [help|list|info minigame|<start|stop|force|status> <rotation>|next <rotation> <minigame>|reload]"
    aliases: [minigame, mm]
permissions:
  minigamemanager.*:
    description: "Gives access to all MinigameManager commands"
    children:
      minigamemanager.admin: true
      minigamemanager.join: true
      minigamemanager.join.others: true
      minigamemanager.leave: true
      minigamemanager.leave.others: true
  minigamemanager.admin:
    description: "Gives access to admin commands"
    children:
      minigamemanager.admin.help: true
      minigamemanager.admin.list: true
      minigamemanager.admin.reload: true
      minigamemanager.admin.start: true
      minigamemanager.admin.stop: true
      minigamemanager.admin.status: true
      minigamemanager.admin.info: true
      minigamemanager.admin.next: true
  minigamemanager.admin.help:
    description: "Allow player to view the help page"
    default: op
  minigamemanager.admin.list:
    description: "Allow player to view the list of minigames"
    default: op
  minigamemanager.admin.reload:
    description: "Allow player to reload the configs"
    default: op
  minigamemanager.admin.start:
    description: "Allow player to start rotation cycles"
    default: op
  minigamemanager.admin.stop:
    description: "Allow player to stop rotation cycles"
    default: op
  minigamemanager.admin.status:
    description: "Allow player to view the status of a rotation"
    default: op
  minigamemanager.admin.info:
    description: "Allow player to view information about a minigame"
    default: op
  minigamemanager.admin.next:
    description: "Allow player to set the next minigame in a rotation"
    default: op
  minigamemanager.join:
    description: "Allow player to join games"
    default: true
  minigamemanager.join.others:
    description: "Allow player to have other players join games"
    default: op
    children:
      minigamemanager.join: true
  minigamemanager.leave:
    description: "Allow player to leave games"
    default: true
  minigamemanager.leave.otehrs:
    description: "Allow player to have other players leave games"
    default: op
    minigamemanager.leave: true
