# The map name
map1:
  # Optional section for displaying the name and author of the map. Can be omitted if no info is present, but both must be set if one is set
  mapinfo:
    # Generic arena name and author for example
    name: Arena
    author: the Server Admins
  chests: []
  # Spawn locations
  spawns:
    # The spawns can be named anything to help keep yourself organized
    center:
      # The world, x, y, z, yaw, and pitch to be spawned at. Typically, world is identical for all of these.
      world: world
      x: 0
      y: 90
      z: 0
      yaw: 0
      pitch: 0
    not_center:
      world: world
      x: 10
      y: 90
      z: 10
      yaw: 0
      pitch: 0
