name: MinigameManager
version: 0.0.1
description: "Minigame API and rotation handler"
main: me.donkeycore.minigamemanager.core.MinigameManager
author: DonkeyCore
commands:
  join:
    description: "Join the minigame rotation"
    permission: minigamemanager.join
    usage: "§cUsage: /<command> [rotation]"
  leave:
    description: "Leave the minigame rotation"
    permission: minigamemanager.leave
    usage: "§cUsage: /<command>"
  minigamemanager:
    description: "Main plugin administration command"
    permission: minigamemanager.admin
    usage: "§cUsage: /<command> help"
    aliases: [minigame, mm]
permissions:
  minigamemanager.*:
    description: "Gives access to all MinigameManager commands"
    children:
      minigamemanager.admin: true
      minigamemanager.join: true
      minigamemanager.join.others: true
      minigamemanager.leave: true
      minigamemanager.leave.others: true
  minigamemanager.admin:
    description: "Gives access to admin commands"
    default: op
  minigamemanager.join:
    description: "Allow player to join games"
    default: true
  minigamemanager.join.others:
    description: "Allow player to have other players join games"
    default: op
    children:
      minigamemanager.join: true
  minigamemanager.leave:
    description: "Allow player to leave games"
    default: true
  minigamemanager.leave.otehrs:
    description: "Allow player to have other players leave games"
    default: op
    minigamemanager.leave: true
